AWSTemplateFormatVersion: '2010-09-09'
Description: 'Basic template to create an EC2 instance and a security group.'

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-1234567890abcdef0
      KeyName: MyKeyPair
      SecurityGroups:
        - !Ref MySecurityGroup

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Enable SSH access'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: 'The Instance ID of the created EC2 instance'
    Value: !Ref MyEC2Instance

  SecurityGroupId:
    Description: 'The ID of the created security group'
    Value: !Ref MySecurityGroup